### ISSUE TITLE
cbz support broken in some cases

### ISSUE THREAD

**Issue by narayandesai** [codedread/kthoom#36] opened 2020-04-22 04:23 UTC
I tried using kthoom on a few cbz files, and loading worked inconsistently. For some files, the console displays a message about 0 pages loaded, and the gui seems stuck in a weird state. Other files seem to work fine. Any pointers what I should do to try to fix this?

**Comment by codedread** [comment] 2020-04-22 04:34
Hi there - it would be great to get an example cbz file that doesn't work.  Can you send me one (or link me to drive/dropbox)?

**Comment by narayandesai** [comment] 2020-04-22 06:03
These are files i bought on comixology, so i'd prefer not. But i'm capable enough I could do debug runs and so forth if there are debug flags to turn up, or you could point me at a debug version to run. Sorry to be difficult; I'd do more to debug directly myself, but I don't have any js knowledge.

**Comment by codedread** [comment] 2020-04-22 08:58
No worries - even if you point me at a comic book, I might consider purchasing just to debug :-)  Unfortunately there are no debug flags for this, just looking at the dev tools / JS console may give you some clue to the errors, or setting breakpoints.

**Comment by codedread** [comment] 2020-04-30 03:51
Hi @narayandesai - if you want to try out the latest kthoom, I added a debug parameter that might de-mystify why some books are not loading.  Add debug=true to the URL and let me know if you see anything useful in the JS console.  Thanks!

**Comment by narayandesai** [comment] 2020-04-30 04:28
Thanks! Sorry I've been slow in responding. adding ?debug=true to the url doesn't seem to make it more verbose, but here are the logs in the js console.

Here's a trace of one: 
Book = 'AFlagg01_1418163538.cbz'
book-binder.js:121   using archive/unzip.js
book-binder.js:122   unarchiving done in 0.642s
comic-book-binder.js:100   number of pages = 0
book-viewer.js:206 updateLayout() before current page is loaded

Wasted Space 9 from Vault comics on comixology has a similar issue, but other cbz files from Comixology work fine. I'm not sure what the pattern is.

**Comment by codedread** [comment] 2020-04-30 21:30
Hm, I forgot to upload the latest source to my website (codedread.com the link in the readme).  Can you try again?

If you were using the latest code from head yesterday and you're still not seeing debug output, then I suspect that the way the Service Worker was implemented (for issue #23) makes it so that the cached version is preferred over the network version, so you're probably not seeing thee latest updates :-/

I've filed Issue #38 for this.

**Comment by narayandesai** [comment] 2020-04-30 21:46
Here you go: 
updateLayout() before current page is loaded
book-binder.js:149 Zip Local File Header:
book-binder.js:149  version=20
book-binder.js:149  general purpose=2056
book-binder.js:149  compression method=8
book-binder.js:149  last mod file time=34442
book-binder.js:149  last mod file date=20200
book-binder.js:149  crc32=1014480108
book-binder.js:149  compressed size=819420508
book-binder.js:149  uncompressed size=1112613436
book-binder.js:149  file name length=6
book-binder.js:149  extra field length=0
book-binder.js:149  filename = '01.jpg'
book-binder.js:126 Book = 'Wasted-Space--9.cbz'
book-binder.js:127   using archive/unzip.js
book-binder.js:128   unarchiving done in 0.173s
comic-book-binder.js:100   number of pages = 0
book-viewer.js:206 updateLayout() before current page is loaded

**Comment by codedread** [comment] 2020-05-01 00:15
Ok, I bought the comic and took a look.  It seems to be because there are data descriptors, which has a TODO in our unzip code:

    // TODO: deal with data descriptor if present (we currently assume no data descriptor!)
    // "This descriptor exists only if bit 3 of the general purpose bit flag is set"
    // But how do you figure out how big the file data is if you don't know the compressedSize
    // from the header?!?

I filed a bug on the bitjs library (which I also own) to fix this, but not sure how I will do that yet:  https://github.com/codedread/bitjs/issues/19

**Comment by codedread** [comment] 2020-05-01 07:20
Ok, I think the fix for that unzip issue should be in now.  Unfortunately the Service Worker is still caching things in a not-great way, so I'll try to fix that tomorrow (maybe unregister the existing service worker and then re-install one that prefers network before cache).

**Comment by codedread** [comment] 2020-05-01 07:21
Actually I'll leave this open in case @narayandesai can confirm he can open all his books.

**Comment by codedread** [comment] 2020-05-14 03:09
Ok, I'm closing this.  Reopen if a problem is found!

**Closed by codedread** 2020-05-14 03:09 UTC
